version: "3.9"
services:
  redis:
    image: redis:alpine
    volumes:
      - user-service-volume:/redis
    restart: on-failure
  user-service:
    image: registry.digitalocean.com/cs3219-g35-peerprep/user-service:latest
    ports:
      - 8000:8000
    environment:
      - REDIS_URI=redis
    depends_on:
      - redis
    restart: on-failure
  frontend:
    image: registry.digitalocean.com/cs3219-g35-peerprep/frontend:latest
    ports:
      - 80:3000
    environment:
      - REACT_APP_URI_USER_SVC=http://${IP}:8000
    restart: on-failure
volumes:
  user-service-volume:
