version: "3.9"
services:
  redis:
    image: redis:alpine
    volumes:
      - user-service-volume:/redis
    restart: on-failure

  user-service:
    image: registry.digitalocean.com/cs3219-g35-peerprep/user-service:latest
    ports:
      - 80:8000
    environment:
      # env variables read in from env file
      - ENV
      - DB_CLOUD_URI
      - TOKEN_SECRET
      # not read in from env file
      - REDIS_URI=redis
    depends_on:
      - redis
    restart: on-failure

volumes:
  user-service-volume:
