version: "3.9"
services:
  redis:
    image: redis:alpine
    volumes:
      - user-service-volume:/redis
  user-service:
    image: registry.digitalocean.com/cs3219-g35-peerprep/peerprep-user-service:latest
    ports:
      - 8000:8000
    environment:
      # Read in from shell's env config
      - ENV
      - DB_CLOUD_URI
      - TOKEN_SECRET
      # Not read in from shell
      - REDIS_URI=redis
    depends_on:
      - redis
volumes:
  user-service-volume:
