version: "3.9"
services:
  redis:
    image: redis:alpine
    volumes:
      - collaboration-service-volume:/redis
    restart: on-failure

  collaboration-service:
    image: registry.digitalocean.com/cs3219-g35-peerprep/collaboration-service:latest
    ports:
      - 80:8400
    environment:
      # env variables read in from env file
      - ENV
      - DB_CLOUD_URI
      # not read in from env file
      - REDIS_URI=redis
    depends_on:
      - redis
    restart: on-failure

volumes:
  collaboration-service-volume:
